'use client'

import { motion } from 'framer-motion'
import { Shield, Lock, Zap, Star, Users, Image as ImageIcon } from 'lucide-react'
import AnimatedCounter from '@/components/ui/AnimatedCounter'
import BeforeAfterSlider from '@/components/ui/BeforeAfterSlider'

// Before/After showcase pairs - illustrative mockups (generated by
// scripts/generate-showcase-images.js), not real customer photos. We
// don't have real restoration results to show, so these are styled
// "aged photo" vs "restored photo" demo art rather than a claim about
// any specific photo.
const SHOWCASE_PAIRS = [
  {
    before: '/images/showcase/family-restore-before.png',
    after: '/images/showcase/family-restore-after.png',
    label: 'Phục hồi ảnh gia đình',
  },
  {
    before: '/images/showcase/quality-upgrade-before.png',
    after: '/images/showcase/quality-upgrade-after.png',
    label: 'Nâng cấp chất lượng',
  },
]

const TRUST_BADGES = [
  { icon: Shield, label: 'Bảo mật SSL', desc: 'Dữ liệu được mã hóa' },
  { icon: Lock, label: 'An toàn dữ liệu', desc: 'Không chia sẻ ảnh' },
  { icon: Zap, label: 'Xử lý nhanh', desc: 'AI thế hệ mới' },
]

export default function SocialProofSection() {
  return (
    <section className="py-20 px-4">
      <div className="max-w-6xl mx-auto">
        {/* Stats Counter */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-bold gradient-text mb-8">
            Được Tin Tưởng Bởi Hàng Ngàn Người Dùng
          </h2>
          <div className="grid grid-cols-3 gap-8 max-w-2xl mx-auto">
            <div className="text-center">
              <AnimatedCounter
                end={10000}
                suffix="+"
                className="text-3xl md:text-4xl font-bold text-primary"
              />
              <p className="text-sm text-gray-600 mt-1">Ảnh đã xử lý</p>
            </div>
            <div className="text-center">
              <AnimatedCounter
                end={2500}
                suffix="+"
                className="text-3xl md:text-4xl font-bold text-purple-600"
              />
              <p className="text-sm text-gray-600 mt-1">Người dùng</p>
            </div>
            <div className="text-center">
              <AnimatedCounter
                end={98}
                suffix="%"
                className="text-3xl md:text-4xl font-bold text-green-600"
              />
              <p className="text-sm text-gray-600 mt-1">Hài lòng</p>
            </div>
          </div>
        </motion.div>

        {/* Before/After Gallery */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.2 }}
          className="mb-16"
        >
          <h3 className="text-2xl font-bold text-center mb-8">
            Kết Quả Thực Tế
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {SHOWCASE_PAIRS.map((pair, idx) => (
              <div key={idx} className="space-y-2">
                <BeforeAfterSlider
                  beforeImage={pair.before}
                  afterImage={pair.after}
                />
                <p className="text-center text-sm text-gray-600 font-medium">{pair.label}</p>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Trust Badges */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.4 }}
          className="flex flex-wrap justify-center gap-6"
        >
          {TRUST_BADGES.map(({ icon: Icon, label, desc }) => (
            <div
              key={label}
              className="flex items-center gap-3 px-5 py-3 bg-white/80 backdrop-blur-sm rounded-xl border border-gray-200 shadow-sm"
            >
              <div className="w-10 h-10 bg-primary/10 rounded-full flex items-center justify-center">
                <Icon className="w-5 h-5 text-primary" />
              </div>
              <div>
                <p className="text-sm font-semibold text-gray-800">{label}</p>
                <p className="text-xs text-gray-500">{desc}</p>
              </div>
            </div>
          ))}
        </motion.div>
      </div>
    </section>
  )
}
